# Build latest release and publish on PyPI
name: Build and Publish
on:
  workflow_dispatch: # TODO change to release when ready

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
           fetch-depth:

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build dist/
        run: |
          cd ${{ github.workspace }}
          python -m build
          ls dist

