# Build latest release and publish on PyPI
name: Build and Publish
on:
  workflow_dispatch: # TODO change to release when ready

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
           fetch-depth:

      - name: Set up Python
        uses: actions/setup-python@v4
          with:
            python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build dist/
        run: |
          cd ${{ github.workspace }}
          python -m build
          #ls dist

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          ###### Test PyPI ########

