# Create a tag and write it's string to VERSION file
name: Tag a Version
on: 
  workflow_dispatch:
    inputs:
      vers_str:
        type: string
        description: "The semantic version string for this tag"
        required: true

jobs:
  Tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
           fetch-depth: 0    # get tags as well

      - name: Rewrite VERSION
        run: |
          cd ${{ github.workspace }}/src/htlfc
          vers=${{ github.event.inputs.vers_str }}
          echo $vers > VERSION

      - name: Commit from runner to repository
        run: |
          cd ${{ github.workspace }}
          git add src/htlfc/VERSION
          git config user.name "Workflow: tag-version.yaml"
          git config user.email "<>"
          git commit -m "Rewrite VERSION with new tag"
          git push

      - name: Create and push tag
        run: |
          cd ${{ github.workspace }}
          git tag $vers -a
          git push --tags

