name: Tag and Release
###### This is a Work in Progress #######
on: 
  workflow_dispatch:
    inputs:
      vers_str:
        type: string
        description: "The semantic version string for this release"
        required: true

jobs:
  Tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        run: |
          echo "The ${{ github.repository }} repository has been cloned to the runner."
          echo "Version string input was ${{ github.event.inputs.vers_str }}"

