name: Version Update
# Rewrite src/htlfc/VERSION with incremental value
on: [push, workflow_dispatch]

jobs:
  New-Version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
           fetch-depth: 0    # get tags as well
      - name: Rewrite VERSION
        run: |
          cd ${{ github.workspace }}/src/htlfc
          vers=$(git describe)
          echo $vers > VERSION

      - name: Commit from runner to repository
        run: |
          #echo $PWD
          git add src/htlfc/VERSION
          git config user.name "Workflow: version-update.yaml"
          git config user.email "<>"
          git commit -m "Rewrite VERSION with last commit"
          git push origin master
